# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "4a366f9df9378b70045b48f718f5dd98"
name = "atlasheadrest"
handle = "atlasheadrest"
application_url = "https://some-purchasing-literacy-andale.trycloudflare.com"
embedded = true

[build]
automatically_update_urls_on_dev = true
dev_store_url = "omartestings.myshopify.com"
include_config_on_deploy = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_customers,read_discounts,write_customers,write_discounts,write_products"

[auth]
redirect_urls = [
  "https://some-purchasing-literacy-andale.trycloudflare.com/auth/callback",
  "https://some-purchasing-literacy-andale.trycloudflare.com/auth/shopify/callback",
  "https://some-purchasing-literacy-andale.trycloudflare.com/api/auth/callback"
]

[webhooks]
api_version = "2024-07"

  [[webhooks.subscriptions]]
  uri = "https://atlasheadrestapp-ff62d1dfdf21.herokuapp.com/webhooks/customers/data_request"
  compliance_topics = [ "customers/data_request" ]

  [[webhooks.subscriptions]]
  uri = "https://atlasheadrestapp-ff62d1dfdf21.herokuapp.com/webhooks/customers/redact"
  compliance_topics = [ "customers/redact" ]

  [[webhooks.subscriptions]]
  uri = "https://atlasheadrestapp-ff62d1dfdf21.herokuapp.com/webhooks/shop/redact"
  compliance_topics = [ "shop/redact" ]

[app_proxy]
url = "https://some-purchasing-literacy-andale.trycloudflare.com/app/atlas"
subpath = "atlas-proxy"
prefix = "apps"

[pos]
embedded = false
